### ISSUE TITLE
It doesn't works for me

### ISSUE THREAD

**Issue by brainsam** [nutso/redmine-plugin-recurring-tasks#104]
Hi! 
Maybe I'm doing something wrong, but after git clone and installation this plugin I see in menu:
translation missing: en.label_recurring_tasks

If I try to configure plugin in Administration - Plugins I see 404 Error 
```
Started GET "/settings/plugin/recurring_tasks" for 127.0.0.1 at 2016-03-23 11:17:58 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"recurring_tasks"}
  Current user: mois (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (33.1ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.1ms)
Completed 404 Not Found in 284ms (Views: 79.9ms | ActiveRecord: 154.5ms)
```
when i try to open Project - recurring tasks I see  "Page no found" error:

```
Started GET "/projects/test-version-proj/recurring_tasks" for 127.0.0.1 at 2016-03-23 11:06:57 +0000

ActionController::RoutingError (uninitialized constant RecurringTasksController):
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `const_get'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `block in constantize'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `each'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `inject'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `constantize'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:72:in `controller_reference'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:62:in `controller'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:41:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
  vendor/bundle/ruby/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
  vendor/bundle/ruby/2.1.0/gems/unicorn-5.0.1/bin/unicorn_rails:209:in `<top (required)>'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
```

Any suggestions?

**Comment by nutso** [comment]
What is the name of the folder with the recurring tasks plugin (inside the 'plugins' directory on your Redmine installation)?

**Comment by brainsam** [comment]
/volume1/docker/redmine-test/plugins/redmine-plugin-recurring-tasks

**Comment by nutso** [comment]
Instead of "redmine-plugin-recurring-tasks", please rename the folder to "recurring_tasks"
