### ISSUE TITLE
Support for Redmine 3.3.x required.

### ISSUE THREAD

**Issue by amityk77** [nutso/redmine-plugin-recurring-tasks#109]
Though it was mentioned that it officially support Redmine till 3.0, but I was somehow able to install it in 3.2.x.

But, after upgrading to 3.3.0, it does not work.

Please can you provide for latest Redmine version.

**Comment by nutso** [comment]
I am running it without any issues on Redmine 3.3.0. Can you provide more information as to what does not work?

**Comment by jmlagace** [comment]
Using Redmine 3.3.0.stable here and having issues as well. 

This is the error I get:

Started GET "/projects/bbv-maintenance/recurring_tasks" for 127.0.0.1 at 2016-09-29 10:34:02 +0000

```
ActionController::RoutingError (uninitialized constant RecurringTasksController):
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in `const_get'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in `block in constantize'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `inject'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:60:in `controller'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:39:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
  vendor/bundle/ruby/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
  vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'

```

And this is my environment:

```
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.9.3
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.9

```

**Comment by kostajh** [comment]
I'm seeing issues on 3.3.1. When I try to access the global Recurring Tasks menu or the per-project item, I see:

```
app_1        | LoadError (Unable to autoload constant RecurringTasksController, expected /app/plugins/recurring_tasks/app/controllers/recurring_tasks_controller.rb to define it):
app_1        |   activesupport (4.2.7.1) lib/active_support/dependencies.rb:495:in `load_missing_constant'
app_1        |   activesupport (4.2.7.1) lib/active_support/dependencies.rb:184:in `const_missing'
app_1        |   activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:261:in `const_get'
app_1        |   activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:261:in `block in constantize'
app_1        |   activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:259:in `each'
app_1        |   activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:259:in `inject'
app_1        |   activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:259:in `constantize'
app_1        |   activesupport (4.2.7.1) lib/active_support/dependencies.rb:566:in `get'
app_1        |   activesupport (4.2.7.1) lib/active_support/dependencies.rb:597:in `constantize'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:60:in `controller'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:39:in `serve'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
app_1        |   rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
app_1        |   request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
app_1        |   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
app_1        |   rack (1.6.4) lib/rack/etag.rb:24:in `call'
app_1        |   rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
app_1        |   rack (1.6.4) lib/rack/head.rb:13:in `call'
app_1        |   actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
app_1        |   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
app_1        |   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
app_1        |   activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
app_1        |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
app_1        |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
app_1        |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
app_1        |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
app_1        |   railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
app_1        |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
app_1        |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
app_1        |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
app_1        |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
app_1        |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
app_1        |   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
app_1        |   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
app_1        |   activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
app_1        |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
app_1        |   actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
app_1        |   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
app_1        |   railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
app_1        |   railties (4.2.7.1) lib/rails/application.rb:165:in `call'
app_1        |   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
app_1        |   puma (3.6.0) lib/puma/configuration.rb:225:in `call'
app_1        |   puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
app_1        |   puma (3.6.0) lib/puma/server.rb:415:in `process_client'
app_1        |   puma (3.6.0) lib/puma/server.rb:275:in `block in run'
app_1        |   puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

And my environment:

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    development
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  recurring_tasks                2.0.0-pre
  redmine_emojibutton            0.4.1
  redmine_github_hook            2.2.0
  redmine_hotkeys_js             0.0.5
  redmine_mentions               0.0.1
  redmine_savas_customizations   0.1.0
  redmine_slack                  0.2
```

**Comment by akurutin** [comment]
just rename "redmine-plugin-recurring-tasks-master" to reccuring_tasks
