### ISSUE TITLE
Error during execution of redmine:recur_tasks (conflict with Luxury Buttons plugin)

### ISSUE THREAD

**Issue by darioo** [nutso/redmine-plugin-recurring-tasks#61]
Hello,

I have problems with execution of redmine:recur_tasks  (redmine 2.5.1)

I have got an error:

```
[webadm@redmine01 redmine]$ rake RAILS_ENV=production redmine:recur_tasks
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.4-compliant syntax, but you are running 2.1.1.
Checking for Redmine recurring tasks.
rake aborted!
Validation failed: You couldn`t save issues with this tracker
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/validations.rb:56:in `save!'
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/transactions.rb:264:in `block in save!'
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/usr/local/inp/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.17/lib/active_record/transactions.rb:264:in `save!'
/usr/local/inp/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:251:in `recur_issue_if_needed!'
/usr/local/inp/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:282:in `block in add_recurrences!'
/usr/local/inp/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:281:in `each'
/usr/local/inp/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:281:in `add_recurrences!'
/usr/local/inp/redmine/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/inp/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/inp/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:recur_tasks
(See full trace by running task with --trace)
```

What thas it meen? How can I manage it?

Best Regard
DK

**Comment by quanvn** [comment]
I confirm that I get the same problem even with the newest version dated 15 June 2015

**Comment by quanvn** [comment]
I find this way to work around and quite sensible for me. 

In def recur_issue_if_needed!, just after      while need_to_recur? add two lines to switch user to author of the issue

old_current_user = User.current
 User.current = issue.author

And after save!, add this to restore user
User.current = old_current_user


This allow the new recurring is created with the same user as original one

**Comment by nutso** [comment]
Integrated into develop; are you also using the Luxury Button plugin? I am not seeing where I can set the tracker allowed_to_roles property for testing.

**Comment by nutso** [comment]
Looking at the Luxury Buttons plugin demo, it does look like this is specific to a conflict with that plugin. 

I pushed the fix to master. Can someone confirm that this is resolved?

**Comment by quanvn** [comment]
Thanks Nutso. It works.
